version: '3'

services:
  mongo-to-clickhouse:
    build: 
      context: ../mongo-to-clickhouse
      dockerfile: Dockerfile
    container_name: lrd_m2c
    volumes:
      - ./config-dev.yml:/app/config-dev.yml
      - ./config-prod.yml:/app/config-prod.yml
    depends_on:
      - db
    networks:
      - lrd-network

  opt-out:
    build:
      context: ../opt-out
      dockerfile: Dockerfile
    container_name: lrd_opt_out
    depends_on:
      - db
    networks:
      - lrd-network

  db:
    image: postgres:latest
    container_name: lrd_db
    env_file:
      - .env
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data
    networks:
      - lrd-network
    ports:
      - "15432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:

networks:
  lrd-network: